name: Deploy to NuxtHub
on: push

jobs:
  deploy:
    name: "Deploy to NuxtHub"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Set up icons for branch
        run: |
          echo "Current branch: ${GITHUB_REF##*/}"

          # Use GITHUB_REF parameter expansion to extract branch name
          BRANCH_NAME="${GITHUB_REF##*/}"
          echo "Branch name from GITHUB_REF: $BRANCH_NAME"

          if [ "$BRANCH_NAME" = "main" ]; then
            echo "Setting up production icons..."
            cp -r public/icons-production/* public/ || echo "No production icons found"
            echo "NODE_ENV=production" >> $GITHUB_ENV
            echo "NUXT_PUBLIC_APP_ENV=production" >> $GITHUB_ENV
          elif [ "$BRANCH_NAME" = "test" ]; then
            echo "Setting up preview icons..."
            cp -r public/icons-preview/* public/ || echo "No preview icons found"
            echo "NODE_ENV=development" >> $GITHUB_ENV
            echo "NUXT_PUBLIC_APP_ENV=preview" >> $GITHUB_ENV
          else
            echo "Unknown branch: $BRANCH_NAME, defaulting to preview"
            cp -r public/icons-preview/* public/ || echo "No preview icons found"
            echo "NODE_ENV=development" >> $GITHUB_ENV
            echo "NUXT_PUBLIC_APP_ENV=preview" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Install dependencies
        run: pnpm install

      - name: Build & Deploy to NuxtHub
        uses: nuxt-hub/action@v2
        with:
          project-key: provmaterial-e54o
