name: Sync Test Branch

on:
  push:
    branches:
      - main

jobs:
  sync-test-branch:
    name: "Sync main to test branch"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push changes to test when main is updated
        if: github.ref == 'refs/heads/main'
        run: |
          git fetch origin
          git checkout test
          git merge -X theirs main
          git push origin test
